"""add project_items

Revision ID: d094beace22e
Revises: 39022ada9a54
Create Date: 2026-06-14 06:52:10.169669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd094beace22e'
down_revision: Union[str, None] = '39022ada9a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['project_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_items_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_items_parent_id'))
        batch_op.drop_index(batch_op.f('ix_project_items_company_id'))

    op.drop_table('project_items')
    # ### end Alembic commands ###
